#!/usr/bin/env bash
# relevio: regenerate docs/handoff/INDEX.md from every handoff on every branch.
#
# INDEX.md is a GENERATED file. It is never hand-edited and never merged by
# hand: on a conflict, rerun this script and commit the result. It is rebuilt
# from the headers of the handoff files found across `git log --all` plus the
# working tree, so it lists sessions whose handoff has not been merged yet.
#
# Usage: relevio-index.sh [--main <ref>] [--stdout]
#   --main <ref>   integration branch to measure lanes against (default:
#                  origin/main, or origin/HEAD; also settable via RELEVIO_MAIN)
#   --stdout       print the index instead of writing docs/handoff/INDEX.md
#
# Exit 0 = index written. Exit 2 = a handoff header is malformed, or the
# integration branch could not be resolved; in both cases INDEX.md is left
# exactly as it was.
set -euo pipefail

. "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/relevio-handoffs-lib.sh"

MAIN_ARG=""; TO_STDOUT=no
while [ $# -gt 0 ]; do
  case "$1" in
    --main) [ $# -ge 2 ] || die "--main needs a ref"; MAIN_ARG="$2"; shift 2 ;;
    --stdout) TO_STDOUT=yes; shift ;;
    -h|--help) relevio_usage "${BASH_SOURCE[0]}"; exit 0 ;;
    *) die "unknown argument: $1 (usage: relevio-index.sh [--main <ref>] [--stdout])" ;;
  esac
done

TOP="$(relevio_top)"
resolve_main "$MAIN_ARG"
load_catalog

ROWS="$(board_rows)"
LANES="$(printf '%s' "$ROWS" | grep -c '' || true)"

render() {
  cat <<'HEAD'
# Handoff library index

This file is GENERATED by relevio (`relevio-index.sh`): never edit it by hand.
It is rebuilt from the metadata header of every handoff found on ANY branch
(`git log --all`) plus the working tree, so it also lists sessions whose
handoff is not merged yet. If it looks stale, or if git reports a merge
conflict on it, do not resolve anything by hand: rerun the script and commit
the result.

    bash .claude/scripts/relevio-index.sh              # script install
    bash "$CLAUDE_PLUGIN_ROOT/scripts/relevio-index.sh"  # plugin install

**Active lanes** is the team board: one row per branch that still has open
work. **Catalog** is the full history: every session ever closed, whichever
branch it happened on.

How to find something:
1. Scan the tables below (dates, branches, areas, topics, summaries).
2. Full-text search the handoffs: `grep -ri "<topic>" docs/handoff/`.
3. Which sessions touched a file or directory, and who has open work on it:
   `bash .claude/scripts/relevio-trace.sh <path>`.
4. Want the code trail? `git log <first>^..<last>` with the row's commit range
   (the `^` is needed: `a..b` would drop the session's own first commit).
5. Need the full reasoning? Reopen the matching conversation from your session
   list: it has everything the handoff summarized.

A handoff survives only while git can still reach it. Push your branch and get
it merged: a handoff committed on a branch that is deleted before merging
disappears from this index along with the branch.

## Active lanes
HEAD
  if [ "$LANES" -eq 0 ]; then
    if [ "$REPO_UNBORN" = yes ]; then
      printf '\n_No active lanes: this repository has no commits yet._\n'
    else
      printf '\n_No active lanes: every branch with a handoff is merged into `%s`, or its branch is gone._\n' "$MAIN"
    fi
  else
    printf '\nBranches with handoffs that still exist and are not yet merged into `%s`.\n\n' "$MAIN"
    echo '| Branch | Dev(s) | Last handoff | Areas | Ahead of main | Note |'
    echo '|--------|--------|--------------|-------|---------------|------|'
    # Field 3 is the date, kept in the record because the rows are sorted by it,
    # but not printed: the filename in field 4 already starts with it.
    printf '%s\n' "$ROWS" | awk -F'\t' '{ printf("| `%s` | %s | %s | %s | %s | %s |\n", $1, $2, $4, $5, $6, $7) }'
  fi
  printf '\n## Catalog\n\n'
  if [ "$CATALOG_COUNT" -eq 0 ]; then
    printf '_No handoffs yet: this project has not closed a session._\n'
  else
    printf 'Every session, oldest first (%s in total).\n\n' "$CATALOG_COUNT"
    echo '| Date | Session (conversation name) | Handoff file | Dev | Branch | Areas | Commits | Topics | Summary |'
    echo '|------|-----------------------------|--------------|-----|--------|-------|---------|--------|---------|'
    printf '%s' "$CATALOG" | awk -F'\t' '$1 != "" {
      f = $1; sub(/.*\//, "", f)
      printf("| %s | %s | %s | %s | `%s` | %s | %s | %s | %s |\n", $2, $3, f, $4, $5, $6, $7, $8, $9)
    }'
  fi
}

if [ "$TO_STDOUT" = yes ]; then
  render
  exit 0
fi

out="$TOP/docs/handoff/INDEX.md"
mkdir -p "$TOP/docs/handoff"
# Render to a temporary file first: a run that dies half-way must not leave a
# truncated index behind.
tmp="$out.relevio-tmp.$$"
trap 'rm -f "$tmp"' EXIT
render > "$tmp"
mv "$tmp" "$out"
trap - EXIT
echo "relevio-index: $CATALOG_COUNT handoff(s), $LANES active lane(s) -> docs/handoff/INDEX.md"
